name: Run Apartment QA Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest with preinstalled Chrome
        env:
          DISPLAY: :99
        run: |
          google-chrome --version
          chromedriver --version
          pytest test_apartments.py --tb=short
